### ISSUE TITLE
Doc

### ISSUE THREAD

**Issue by CRY-D** [astrapi69/swing-app-ui-template#1]
Could you please provide examples how to use the library?

**Comment by astrapi69** [comment]
Hello @CRY-D,

i extracted this template from existing projects like mystic-crypt-ui or silent-mouse. If you are in hurry you can have a look at this repositories. But it is still in development mode. I have to implement some automated tasks and insert into the transform method InitialTemplateTest#testRenameToConcreteProject.

When im finished i will let you know through this issue where the documentation is.

**Comment by astrapi69** [comment]
Hi @CRY-D,

i created now a small documentation for it: [Wiki](https://github.com/astrapi69/swing-app-ui-template/wiki)

Have a detailed look and tell me if it helped you.

If you have any question or feedback do not hesitate to contact me
